insert into stock_master (stock_symbol, stock_name, last_price) values ('TSLA', 'Tesla Inc.',                      798.75);
insert into stock_master (stock_symbol, stock_name, last_price) values ('IBIO', 'iBio Inc.',                       0.9161);
insert into stock_master (stock_symbol, stock_name, last_price) values ('NAT',  'Nordic American Tankers Limited', 7.2);
insert into stock_master (stock_symbol, stock_name, last_price) values ('FFIV', 'F5 Networks Inc.',                130.92);
insert into stock_master (stock_symbol, stock_name, last_price) values ('MRNA', 'Moderna Inc.',                    48.05);
insert into stock_master (stock_symbol, stock_name, last_price) values ('KSS',  'Kohls Corporation',              18.6);
insert into stock_master (stock_symbol, stock_name, last_price) values ('NVDA', 'NVIDIA Corporation',              297.08);
insert into stock_master (stock_symbol, stock_name, last_price) values ('USO',  'United States Oil Fund LP',       2.19);
insert into stock_master (stock_symbol, stock_name, last_price) values ('AXSM', 'Axsome Therapeutics Inc.',        95);
insert into stock_master (stock_symbol, stock_name, last_price) values ('VISL', 'Vislink Technologies Inc.',       0.285);
insert into stock_master (stock_symbol, stock_name, last_price) values ('CGC',  'Canopy Growth Corporation',       17.53);
insert into stock_master (stock_symbol, stock_name, last_price) values ('SBUX', 'Starbucks Corporation',           77.74);
insert into stock_master (stock_symbol, stock_name, last_price) values ('BYND', 'Beyond Meat Inc.',                99.63);
insert into stock_master (stock_symbol, stock_name, last_price) values ('YTEN', 'Yield10 Bioscience Inc.', 7.91);
insert into stock_master (stock_symbol, stock_name, last_price) values ('UCO',  'ProShares Ultra Bloomberg Crude Oil', 12.42);
insert into stock_master (stock_symbol, stock_name, last_price) values ('LYV',  'Live Nation Entertainment.', 42.01);
insert into stock_master (stock_symbol, stock_name, last_price) values ('CCL',  'Carnival Corporation & Plc', 12.98);
insert into stock_master (stock_symbol, stock_name, last_price) values ('UAVS', 'AgEagle Aerial Systems Inc.', 1.01);
insert into stock_master (stock_symbol, stock_name, last_price) values ('BBBY', 'Bed Bath & Beyond Inc.', 6.41);
insert into stock_master (stock_symbol, stock_name, last_price) values ('COTY', 'Coty Inc.', 5.44);
insert into stock_master (stock_symbol, stock_name, last_price) values ('WORK', 'Slack Technologies Inc.', 27.31);
insert into stock_master (stock_symbol, stock_name, last_price) values ('AMD',  'Advanced Micro Devices Inc.', 56.49);
insert into stock_master (stock_symbol, stock_name, last_price) values ('RCL',  'Royal Caribbean Cruises Ltd.', 39.47);
insert into stock_master (stock_symbol, stock_name, last_price) values ('QTNT', 'Quotient Limited', 7.59);
insert into stock_master (stock_symbol, stock_name, last_price) values ('GOOG', 'Alphabet Inc.', 275.88);
insert into stock_master (stock_symbol, stock_name, last_price) values ('NXPI', 'NXP Semiconductors N.V.', 97.13);
insert into stock_master (stock_symbol, stock_name, last_price) values ('VSTM', 'Verastem Inc.', 2.105);
insert into stock_master (stock_symbol, stock_name, last_price) values ('GNC',  'GNC Holdings Inc.', 0.74);
insert into stock_master (stock_symbol, stock_name, last_price) values ('TNP',  'Tsakos Energy Navigation Limited', 4.02);
insert into stock_master (stock_symbol, stock_name, last_price) values ('AIM',  'AIM ImmunoTech Inc.', 1.9);
